modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
    modId = "mymod"
    version = "${file.jarVersion}"
    displayName = "MyMod"
    description = '''
        My first Minecraft Forge mod.
    '''

[[dependencies.mymod]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.mymod]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"
